_alexis:
    type: rest
    resource: "@RithisAlexisBundle/Resources/config/routing.yml"

_loginza:
    type: rest
    resource: "@RithisLoginzaBundle/Resources/config/routing.yml"

_profile:
    type: rest
    resource: "@RithisProfilesBundle/Resources/config/routing.yml"
