new_sessions:
    pattern: /sessions/new
    defaults: { _controller: RithisProfilesBundle:Sessions:newSessions }
    requirements:
        _method: GET

post_sesions_check:
    pattern: /sessions/check
    requirements:
        _method: POST

_alexis:
    type: rest
    resource: "@RithisAlexisBundle/Resources/config/routing.yml"

_loginza:
    type: rest
    resource: "@RithisLoginzaBundle/Resources/config/routing.yml"

_profile:
    type: rest
    resource: "@RithisProfilesBundle/Resources/config/routing.yml"
