security:
    providers:
        loginza:
            id: security.user.provider.profiles
        profiles:
            mongodb:
                class: Rithis\ProfilesBundle\Document\Profile

    access_control:
        # anonymous
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sessions(/new)?(\.xml)?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profiles(/new)?(\.xml)?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # not registered
        - { path: ^/session, roles: ROLE_USER }
        - { path: ^/profile/credentials, roles: ROLE_USER }

        # registered
        - { path: ^, roles: ROLE_REGISTERED }

    firewalls:
        secured_area:
            pattern: ^
            anonymous: ~
            loginza: ~
            logout:
                path: /session
                target: /
            form_login:
                provider: profiles
                login_path: /sessions/new
                check_path: /sessions

    role_hierarchy:
        ROLE_SPONSOR: ROLE_REGISTERED
        ROLE_FREE: ROLE_REGISTERED

    encoders:
        Rithis\ProfilesBundle\Document\Profile: sha512
