security:
    providers:
        loginza:
            id: security.user.provider.loginza

    access_control:
        - { path: ^/requests/new$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^, roles: ROLE_USER }

    firewalls:
        secured_area:
            pattern: ^
            anonymous: ~
            loginza: ~
            logout:
                path: /sessions/current
                target: /requests/new
