security:
    providers:
        loginza:
            id: security.user.provider.alexis

    access_control:
        - { path: ^/requests/new$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sessions, roles: ROLE_USER }
        - { path: ^, roles: ROLE_REGISTERED }

    firewalls:
        secured_area:
            pattern: ^
            anonymous: ~
            loginza: ~
            logout:
                path: /sessions/current
                target: /requests/new

    role_hierarchy:
        ROLE_SPONSOR: ROLE_REGISTERED
        ROLE_FREE: ROLE_REGISTERED

    encoders:
        Rithis\AlexisBundle\Security\User: sha512
