parameters:
    mongodb.connection.class: Mongo
    mongodb.class: MongoDb
    session.handler.class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler

services:
    mongodb.connection:
        class: %mongodb.connection.class%

    mongodb:
        class: %mongodb.class%
        factory_service: mongodb.connection
        factory_method: selectDb
        arguments:
            - %mongo_database%

    session.handler:
        class: %session.handler.class%
        arguments:
            - @mongodb.connection
            - { database: %mongo_database%, collection: sessions }

    alexis.s3:
        class: AmazonS3
        arguments:
            - { key: %aws_key%, secret: %aws_secret% }

    alexis.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @alexis.s3
            - %aws_bucket%

    alexis.s3.adapter.acl_aware:
        class: Gaufrette\Adapter\AclAwareAmazonS3
        arguments:
            - @alexis.s3.adapter
            - @alexis.s3
            - %aws_bucket%
        calls:
            - [ setAclConstant, [PUBLIC]]

    alexis.fs:
        class: Gaufrette\Filesystem
        arguments:
            - @alexis.s3.adapter.acl_aware

    alexis.imagine:
        class: Imagine\Gd\Imagine
