parameters:
    profiles.form.choicelist.travel.class: Rithis\ProfilesBundle\Form\ChoiceList\TravelChoiceList
    profiles.form.type.profile.class: Rithis\ProfilesBundle\Form\Type\ProfileType

services:
    profiles.form.choicelist.travel:
        class: %profiles.form.choicelist.travel.class%
        arguments:
            - @mongodb

    profiles.form.type.profile:
        class: %profiles.form.type.profile.class%
        arguments:
            - @profiles.form.choicelist.travel
