loginza_post_sessions:
    pattern: /sessions
    defaults: { _controller: RithisLoginzaBundle:Sessions:postSessions }
    requirements:
        _method: POST

loginza_delete_session:
    pattern: /sessions/current
    requirements:
        _method: DELETE

loginza_remove_session:
    pattern: /sessions/current/remove
    defaults: { _controller: RithisLoginzaBundle:Sessions:removeSession }
    requirements:
        _method: GET
