Rithis\ProfilesBundle\Document\Profile:
    repositoryClass: Rithis\ProfilesBundle\Repository\ProfileRepository
    fields:
        id:
            id: true
            type: id
        email:
            type: string
        passwordHash:
            type: string
        passwordSalt:
            type: string
        nickname:
            type: string
        firstName:
            type: string
        lastName:
            type: string
        avatar:
            type: string
        birthday:
            type: date
        weight:
            type: int
        height:
            type: int
        sex:
            type: string
        about:
            type: string
        budget:
            type: int
        identities:
            type: collection
        roles:
            type: collection
        #preferences:
        #photos:
        #timerange:
        #travels:
