alexis_new_searchrequests:
    pattern: /search-requests/new
    defaults: { _controller: RithisAlexisBundle:SearchRequests:newSearchRequests }
    requirements:
        _method: GET

alexis_post_searchrequests:
    pattern: /search-requests
    defaults: { _controller: RithisAlexisBundle:SearchRequests:postSearchRequests }
    requirements:
        _method: POST

alexis_get_searchrequest:
    pattern: /search-requests/{hash}
    defaults: { _controller: RithisAlexisBundle:SearchRequests:getSearchRequest }
    requirements:
        _method: GET
