_alexis_requests:
    type: rest
    resource: Rithis\AlexisBundle\Controller\RequestsController
    name_prefix: alexis_

mainpage:
    pattern: /
    defaults: { _controller: RithisAlexisBundle:Default:index }
    requirements:
        _method: GET
