TravelBundle_homepage:
    pattern:  /addtravel
    defaults: { _controller: RithisTravelBundle:Travels:addFakeTravel }

_travel_travels:
    type: rest
    resource: Rithis\TravelBundle\Controller\TravelsController
    name_prefix: travel_
