parameters:
#    travel.example.class: Rithis\TravelBundle\Example

services:
#    travel.example:
#        class: %travel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
