<?php

namespace Rithis\TravelBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends DocumentRepository
{
    public function findRandomTravels($quantity)
    {
        $count=$this->createQueryBuilder()
            ->count()
            ->getQuery()
            ->execute();
        if ($quantity>$count)
        {
           $quantity=$count;
        }

        $vals=array();

        while (count($vals)<$quantity)
        {
            $randVal=rand(0,$count-1);
            if (!in_array($randVal,$vals))
            {
                $vals[]=$randVal;
            }
        }

        $result=array();
        $tempResult=array();
        $i=0;
        foreach ($vals as $val)
        {
            $resultItem=$this->createQueryBuilder()
                ->limit(1)
                ->skip($val)
                ->getQuery()
                ->execute();

            foreach ($resultItem as $item)
            {
                $tempResult[]=$item->getId();
                $result[]=$item;
            }
            $i++;
        }


        return $result;
    }

    public function findAllTravels()
    {
        $result=$this->createQueryBuilder()
            ->find()
            ->getQuery()
            ->execute();

        return $result;
    }

}